#配置服务器
server:
  port: 8080
#配置spring
spring:
  datasource:
    name: quaint
    url: jdbc:mysql://127.0.0.1:3306/quaintblog
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #时间转换处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8